### ISSUE TITLE
Cannot decrypt data

### ISSUE THREAD

**Issue by ekardon** [claabs/ubisoft-dmx-decode#1]
I am following your guide step by step, but when I capture data using wireshark, it doesn't decrypt all the traffic. I see some of them decrypted but not all.

I am using win10 and latest frida

**Comment by claabs** [comment]
I started observing the same issue soon after I posted the guide. Not sure what changed, but it seems like a lsass snoop or WireShark issue.

**Comment by ekardon** [comment]
I think i figured it out. Addition to pointing wireshark to keylog.log file, i had to set SSLKEYLOGFILE environment variable with the value of keylog.log file's path. Now it works fine. Also, thanks for the guide
